export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_UPDATE = 'AUTH_UPDATE'
export const UPDATE_LIST = 'UPDATE_LIST'
export const UPDATE_KNOCKS = 'UPDATE_KNOCKS'
